/** Commercial setup acceptance check against a running local app. */
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const url = process.env.BASE_URL ?? 'http://127.0.0.1:5173/';
const out = 'test-results/commercial';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH ?? ['C:/Program Files/Google/Chrome/Application/chrome.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync) });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
const checks = [];
page.on('pageerror', error => errors.push(error.message));
const project = () => page.evaluate(() => JSON.parse(localStorage.getItem('flooring-estimator:project:v1')).project);
const commit = async (name, value) => { const input = page.getByLabel(name, { exact: true }); await input.fill(value); await input.press('Tab'); };
const tab = name => page.locator('nav.tabs').getByRole('button', { name, exact: true }).click();
const orderList = async () => { await tab('Estimate'); await page.getByRole('navigation', { name: 'Estimate sections' }).getByRole('button', { name: 'Order list & costs', exact: true }).click(); };
const money = text => Number(text.replace(/[^0-9.-]/g, ''));
try {
  await page.goto(url);
  await tab('Materials & options');
  await page.getByLabel('Product price basis', { exact: true }).selectOption('per_roll');
  await commit('Price per roll', '800');
  await commit('Priced roll length', '10m');
  await page.getByLabel('Carpet underlay option', { exact: true }).selectOption('pu8');
  await commit('Product wastage allowance', '10');
  let p = await project();
  assert.equal(p.products[0].priceBasis, 'per_roll');
  assert.equal(p.products[0].pricePerRoll, 800);
  assert.equal(p.products[0].pricedRollLength, 10000);
  assert.equal(p.products[0].underlay.pricePerRoll, 60);
  assert.equal(p.products[0].wastageAllowance, 0.1);
  checks.push('Roll pricing, known roll length, underlay preset and waste save from product setup');
  await page.locator('.product-editor').screenshot({ path: `${out}/carpet-setup-desktop.png` });
  await page.getByRole('button', { name: 'Measure a room', exact: true }).click();
  await commit('Room name', 'Lounge');
  await commit('Room length', '5m');
  await commit('Room width', '3m');
  await orderList();
  let covering = page.locator('.bom-line[data-category="floor_covering"]').first();
  assert.equal(await covering.locator('td').nth(2).innerText(), 'roll');
  assert.equal(money(await covering.locator('td').nth(4).innerText()), 800);
  assert.equal(money(await page.locator('.bom-line[data-category="underlay"] td').nth(3).innerText()), 60);
  await page.getByRole('navigation', { name: 'Estimate sections' }).getByRole('button', { name: 'Cutting plans', exact: true }).click();
  assert.equal(await page.locator('.physical-roll').count(), 1);
  assert(await page.locator('.physical-roll-order').getByText('10.00 m to order', { exact: true }).isVisible());
  await page.locator('.physical-roll').screenshot({ path: `${out}/whole-roll-purchase.png` });
  await tab('Materials & options');
  await page.getByLabel('Roll charging method', { exact: true }).selectOption('cut_length');
  await page.getByLabel('Carpet underlay option', { exact: true }).selectOption('none');
  await orderList();
  covering = page.locator('.bom-line[data-category="floor_covering"]').first();
  assert.equal(await covering.locator('td').nth(2).innerText(), 'lm');
  const cutMetres = Number((await covering.locator('td').nth(1).innerText()).split('\n')[0]);
  const cutCost = money(await covering.locator('td').nth(4).innerText());
  assert.equal(cutCost, Math.round(cutMetres * (800 / 10) * 100) / 100);
  assert(cutCost < 800);
  assert.equal(await page.locator('.bom-line[data-category="underlay"]').count(), 0);
  await tab('Materials & options');
  await page.getByLabel('Carpet underlay option', { exact: true }).selectOption('pu8');
  checks.push(`Rendered BOM charges £800 per whole roll or £${cutCost} for ${cutMetres}m of cut length; chosen £60 underlay disappears when excluded`);
  await tab('Settings');
  await page.getByLabel('Labour pricing method', { exact: true }).selectOption('hourly');
  await commit('Hourly labour rate', '50');
  await page.getByRole('button', { name: /How the hours are calculated/ }).click();
  assert(await page.getByText('15 m² ÷ 12 m²/hour', { exact: true }).isVisible());
  p = await project();
  assert.equal(p.prices.labourModel.mode, 'hourly');
  assert.equal(p.prices.labourModel.hourlyRate, 50);
  await page.screenshot({ path: `${out}/settings-desktop.png`, fullPage: false });
  checks.push('Hourly labour settings show a transparent activity calculation');
  for (const width of [1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    const size = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth }));
    assert(size.scroll <= size.viewport + 1, `Settings overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 390, height: 1000 });
  await page.locator('.settings-panel').screenshot({ path: `${out}/settings-mobile.png` });
  await tab('Materials & options');
  await page.getByLabel('Product preset', { exact: true }).selectOption('lvt_click');
  await page.getByRole('button', { name: '+ Add product', exact: true }).click();
  await page.getByLabel('Product laying pattern', { exact: true }).selectOption('herringbone');
  assert.equal(await page.getByLabel('Product cutting wastage', { exact: true }).inputValue(), '20');
  await page.getByLabel('Product price basis', { exact: true }).selectOption('per_m2');
  await commit('Price per square metre', '19');
  p = await project();
  assert.equal(p.products.at(-1).hardFloor.layPattern, 'herringbone');
  assert.equal(p.products.at(-1).pricePerM2, 19);
  for (const width of [1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    const size = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth }));
    assert(size.scroll <= size.viewport + 1, `Product setup overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 390, height: 1000 });
  await page.locator('.product-editor').screenshot({ path: `${out}/herringbone-mobile.png` });
  checks.push('Herringbone LVT and square-metre pack pricing are visible and responsive at 1024/768/390/320px');
  await page.getByRole('button', { name: 'Measure a room', exact: true }).click();
  await commit('Room name', 'Kitchen');
  await commit('Room length', '4m');
  await commit('Room width', '5m');
  await page.getByRole('button', { name: 'Planning overrides', exact: true }).click();
  assert.equal(await page.getByLabel('Lay pattern', { exact: true }).locator('option:checked').innerText(), 'Product default (Herringbone)');
  await orderList();
  const lvt = p.products.at(-1);
  const lvtRow = page.locator('.bom-line[data-category="floor_covering"]').filter({ hasText: lvt.name }).first();
  assert.equal(money(await lvtRow.locator('td').nth(4).innerText()), Math.ceil(24 / lvt.packCoverageM2) * lvt.packCoverageM2 * 19);
  assert((await lvtRow.innerText()).includes('20% cutting wastage'));
  checks.push('Room inherits product herringbone and its priced whole-pack order includes 20% cutting wastage');
  await page.reload();
  p = await project();
  assert.equal(p.prices.labourModel.hourlyRate, 50);
  assert.equal(p.products.at(-1).hardFloor.layPattern, 'herringbone');
  checks.push('Commercial settings persist through reload');
  assert.deepEqual(errors, []);
  await writeFile(`${out}/report.json`, JSON.stringify({ checks, errors }, null, 2));
  console.log(checks.map(check => `PASS ${check}`).join('\n'));
} finally { await browser.close(); }
